apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: BlogApp-ingress
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: BlogApp-service
                port:
                  number: 80
